Add flash notification on form save
PrestaShop/blockwishlist pull request #150
Opened 2022-01-05 08:48 UTC by NeOMakinG

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | There was no notification on save
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27128.
| How to test?      | Try to save the configuration form in the BO
| Possible impacts? | On save notification

2022-01-05 09:04 UTC, PierreRambaud requested changes
Ci is broken :eyes:

2022-01-06 09:16 UTC, PierreRambaud approved these changes

2022-01-10 14:08 UTC, HanaRebaiQA commented
Hello @NeOMakinG 

I have tested this PR. The issue is fixed.

Here the tested cases : 
-Check on PS1782, PS178x and develop branches
**-Check with different languages** (English, Frensh, Arabic, Poland, Turksih, Chine..)
![image](https://user-images.githubusercontent.com/92912932/148779113-906bc1cf-c8fc-4e86-ad0e-a8938a54362f.png)
![image](https://user-images.githubusercontent.com/92912932/148778997-9e086241-95a9-4a20-ab6e-0b992fd699c5.png)

**-Check with multistore**
![image](https://user-images.githubusercontent.com/92912932/148778509-274d8501-78b5-4c2a-9613-342a9131036b.png)

**-Check with responsive**
![image](https://user-images.githubusercontent.com/92912932/148778591-6d83935c-14e2-4f98-a4f3-65c23c4253fe.png)

So, QA :heavy_check_mark: 

Thanks!

2022-01-10 14:21 UTC, merged

2022-01-10 14:21 UTC, NeOMakinG commented
Thanks @HanaRebaiQA