Fixed Number of Products in a WishList (if product is disabled or removed)
PrestaShop/blockwishlist pull request #164
Opened 2022-03-08 15:32 UTC by Progi1984

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fixed Number of Products in a WishList (if product is disabled or removed)
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#27488
| How to test?      | Cf. PrestaShop/PrestaShop#27488

2022-03-09 13:59 UTC, PierreRambaud commented on classes/WishList.php
> +            RIGHT JOIN `' . _DB_PREFIX_ . 'product` p ON p.`id_product` = wp.`id_product`
```suggestion
            INNER JOIN `' . _DB_PREFIX_ . 'product` p ON p.`id_product` = wp.`id_product`
```

2022-03-09 14:00 UTC, PierreRambaud requested changes
Juste one comment, not sure the RIGHT JOIN is the good approach

2022-03-09 15:25 UTC, PierreRambaud approved these changes

2022-03-10 08:19 UTC, NeOMakinG approved these changes

2022-03-10 11:31 UTC, florine2623 requested changes
Hello @Progi1984 ,
Thanks for the PR !

After installing the PR, I can't add any product to my wishlist.


https://user-images.githubusercontent.com/16019289/157653260-ae4a8efc-5fce-4345-92be-51a51dc3c197.mov


Could you check ?
Thanks!

2022-03-11 10:14 UTC, Progi1984 commented
@florine2623 Have you build assets ?

2022-03-14 08:54 UTC, NeOMakinG commented
> Hello @Progi1984 , Thanks for the PR !
> 
> After installing the PR, I can't add any product to my wishlist.
> 
>  Screen.Recording.2022-03-10.at.12.29.44.mov 
> Could you check ? Thanks!

@florine2623 You probably need to reset the module, or test with the develop branch, this problem looks related to the core but not the module

2022-03-14 16:07 UTC, florine2623 approved these changes
Thanks @Progi1984 @NeOMakinG ,

Looking good to me ^^
Numbers in parenthesis match with reality !

2022-03-14 16:08 UTC, merged

2022-03-14 16:09 UTC, Progi1984 commented
Thanks @florine2623