Fix multiple modal open on wishlist list page
PrestaShop/blockwishlist pull request #168
Opened 2022-03-29 15:01 UTC by NeOMakinG

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | When you go to your wishlist lists, when you click on create, it open 2 modals
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Go on my wishlist page and try to click on Create, then close the modal, it should works fine
| Possible impacts? | Wishlist page usage

2022-03-29 15:17 UTC, Progi1984 approved these changes

2022-03-29 15:28 UTC, florine2623 requested changes
Hello @NeOMakinG ,

I have an issue. I can't share, rename or delete a wishlist :
(I have ran `npm install && npm run build`)

https://user-images.githubusercontent.com/16019289/160648086-c435df46-29ef-4af0-aef0-fcf6e37f41d8.mov



Could you check please ? :)
Thanks!

2022-03-30 09:47 UTC, florine2623 approved these changes
Hello @NeOMakinG ,

Thanks for the update, it works like a charm !
QA ✅

2022-03-30 09:48 UTC, merged

2022-03-30 09:48 UTC, Progi1984 commented
Thanks @NeOMakinG & @florine2623