Fixed wishlist display when title is too long
PrestaShop/blockwishlist pull request #185
Opened 2022-09-06 08:49 UTC by nicosomb

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | If the wishlist title is too long, the display is broken
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     |  no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/29213
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/29213
| Possible impacts? | 

I also fixed the display in the popin when clicking on the "add to wishlist" button. 
Thank you @NeOMakinG 

![Capture d’écran 2022-09-06 à 10 23 45](https://user-images.githubusercontent.com/121870/188590467-8143628d-8150-4509-ac6f-6a2d31e05cc6.png)
![Capture d’écran 2022-09-06 à 10 24 02](https://user-images.githubusercontent.com/121870/188590477-ff5a29af-2be7-482e-8a06-15e252b44864.png)

2022-09-06 08:50 UTC, NeOMakinG approved these changes

2022-09-06 09:34 UTC, kpodemski approved these changes

2022-09-06 11:02 UTC, matthieu-rolland approved these changes

2022-09-15 12:39 UTC, florine2623 reviewed
Hello @nicosomb ,

Tested on 1.7.8.x, 8.0.x, develop.

I noticed an extra space when the name of wishlist is 1 big word:

<img width="297" alt="Screenshot 2022-09-15 at 14 25 31" src="https://user-images.githubusercontent.com/16019289/190403368-e13cba24-5791-41f2-a2ce-cff6a9c4abea.png">

Other than that, checked "add to wishlist" popup. It is looking good.
<img width="288" alt="Screenshot 2022-09-15 at 14 25 12" src="https://user-images.githubusercontent.com/16019289/190403815-fdae9da8-e9b6-42e8-8783-53b896e3c3f2.png">


Could you check ?
Thanks!

2022-09-15 14:22 UTC, nicosomb commented
Hello @florine2623. 
I tried on Firefox and Chrome and I can't reproduce it. Could you please send me more details about your environment?

2022-10-06 09:47 UTC, florine2623 commented
Hello @nicosomb ,

Sorry for the late answer.

I retested on Chrome 105.0.5195.125, Firefox and Opera and I reproduced the issue I'm having.
<img width="371" alt="Screenshot 2022-10-06 at 11 38 38" src="https://user-images.githubusercontent.com/16019289/194281857-3deca46d-bedf-4cf0-996d-70f4d3783eb4.png">

More info about my shop:
<img width="591" alt="Screenshot 2022-10-06 at 11 47 05" src="https://user-images.githubusercontent.com/16019289/194282113-0d6530d5-8c52-46d5-91da-b1ee1e57be42.png">


I have well installed the PR:
<img width="369" alt="Screenshot 2022-10-06 at 11 44 46" src="https://user-images.githubusercontent.com/16019289/194281614-bb743e7e-cff8-4242-a262-4e27abefdba2.png">

I have deleted my browser cache and my PrestaShop cache as well.

Tested on 8.0.0. and 1.7.8.x, the issue is the same on both versions.

I hope the info I share can help ^^

2022-12-12 13:18 UTC, kpodemski commented
ping @nicosomb :)

2023-01-10 16:36 UTC, matks requested changes
Changes have been requested

2023-02-17 14:41 UTC, nicosomb commented
Hello @paulnoelcholot. 
I made new tries ... and I still can't reproduce the bug (firefox or chrome). 

![Capture d’écran 2023-02-17 à 15 40 09](https://user-images.githubusercontent.com/121870/219684997-5465fa61-766e-4255-9b73-83003133c701.png)

What can we do to go forward on this issue?

2023-02-19 01:22 UTC, leemyongpakvn commented
@nicosomb I see **florine2623** and **paulnoelcholot** used narrower screen mobiles than yours. Maybe the bug happens with under 380px wide screen.

2023-02-20 10:17 UTC, nicosomb commented
@paulnoelcholot @florine2623 I think that I fixed the bug.

2023-02-21 15:29 UTC, MhiriFaten reviewed
Hello @nicosomb ,

I have checked your PR, and here is my checklist : 

- checked with a sequence of characters **without** spaces :white_check_mark: 
- checked with a sequence of characters **with** spaces      :white_check_mark: 
- checked with Chrome and Firefox                                        :white_check_mark: 
- checked "add to wishlist" popup                                           :x:  


Fixed wishlist display when title is too long :white_check_mark: 

![image](https://user-images.githubusercontent.com/111756615/220384529-e929bab8-3b0e-4468-a057-ad94fb4ffa9c.png)

"add to wishlist" popup                                           :x:  


[Untitled_ Feb 21, 2023 4_27 PM.webm](https://user-images.githubusercontent.com/111756615/220387163-cda1020d-3ac0-4d6c-a379-6d91785b9d90.webm)

Could you recheck it please?

2023-02-21 15:40 UTC, nicosomb commented
@MhiriFaten hmmm what is the issue on your screenshot?

2023-02-21 15:47 UTC, MhiriFaten commented
@nicosomb , 
Contrary, the screenshot is for approve that the issue is well fixed in the wishlist (as it is marked just above the screenshot **Fixed wishlist display when title is too long** :white_check_mark: ).

The problem is in the popup wishlist as shown in the screenrecord.

2023-02-21 16:17 UTC, nicosomb commented
ok 😄 I didn't see the video on my smartphone, but I can see it on my computer. I will have a look on this bug later.

2023-02-23 16:08 UTC, nicosomb commented
@MhiriFaten I tried to reproduce with Firefox and Chrome, but I can't. The popin is well displayed on my side.

2023-03-02 10:48 UTC, SharakPL commented on _dev/front/js/components/List/List.vue
> +          max-width: 70%;
Use of % is the reason for module not being consistent on different screen sizes so please don't use it. Best way to go is use flex on the parent, fixed width/flex-basis on buttons container and let the title fill the rest of the space.

Also it should be tested on v.3.0.0 released recently cause it already impacted wishlist modals.

2023-07-26 13:41 UTC, closed without merging